#!/usr/bin/env bash
#set -u
#set -x

trap "exit;" SIGINT SIGTERM

#brew inventory list
INVENTORY=(
ansible				etcd				kapacitor			node				supervisor
ansible-cmdb			fontconfig			kompose				nomad				terraform
apr				fpp				kops				nsq				terraform-inventory
apr-util			freetype			kubernetes-cli			openssl				terragrunt
asciinema			gd				kubernetes-helm			openssl@1.1			the_silver_searcher
atool				gdbm				libdnet				packer				thefuck
autoconf			gettext				libevent			pcre				tmux
automake			git				libffi				pkg-config			traefik
awscli				gitlab-runner			libgpg-error			python				trash-cli
azure-cli			glib				libidn2				python3				tree
bash				glide				libksba				python@2			vault
bash-completion			gnu-sed				libpng				ranger				watch
bats				go				libssh2				readline			watchexec
boost				go-jira				libtiff				reattach-to-user-namespace	watchman
boost@1.60			godep				libtool				redis				webp
chronograf			graphviz			libunistring			rsync				wget
consul				groovy				libyaml				ruby				wxmac
coreutils			haproxy				luajit				s-lang				xz
cucumber-cpp			htop				lynx				sbt				zookeeper
daq				hugo				midnight-commander		scala				zsh
dep				icu4c				nano				snort				zsh-completions
docker				influxdb			ncurses				sqlite
docker-compose-completion	jpeg				nginx				squid
erlang				juju				nmap				ssh-copy-id 
caskroom/cask/vagrant-manager  caskroom/cask/vagrant            jq
)


   function instBrew (){
      #check is brew is installed, if not then install
         if [ ! -f "/usr/local/bin/brew" ]       # Check if file exists.
            then
         #   eval "$HOMEBREW[$@]"
             /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
         fi
   }

   function instInv () {
         for u in ${INVENTORY[@]}
            do /usr/local/bin/brew install "${u}"
	 done
   }

printf '%s\n' "${INVENTORY[@]}"

instBrew;
instInv;
