#!/usr/bin/env bash
#set -u
#set -x

trap "exit;" SIGINT SIGTERM

#brew inventory list
INVENTORY=(
         ab
         ansible
         ansible-cmdb
         apr
         apr-util
         asciinema
         atool
         autoconf
         automake
         awscli
         azure-cli
         bash
         bash-completion
         bats
         bbl
         boost
         boost@1.60
         bosh-cli
         bosh-init
         cf-cli
         chronograf
         consul
         coreutils
         credhub-cli
         cucumber-cpp
         daq
         delve
         dep
         docker
         docker-compose-completion
         erlang
         etcd
         fontconfig
         fpp
         freetype
         gd
         gdbm
         gettext
         git
         gitlab-ci-multi-runner
         gitlab-runner
         glib
         glide
         gnu-sed
         go
         go-jira
         godep
         gradle
         graphviz
         groovy
         haproxy
         htop
         hub
         hugo
         icu4c
         influxdb
         jpeg
         juju
         kafka
         kapacitor
         kompose
         kube-prompt
         kubernetes-cli
         kubernetes-helm
         libdnet
         libevent
         libffi
         libgpg-error
         libidn2
         libksba
         libpng
         libssh2
         libtiff
         libtool
         libunistring
         libyaml
         logstash
         luajit
         lynx
         maven
         midnight-commander
         nano
         ncurses
         nginx
         nmap
         node
         nomad
         nsq
         openssl
         openssl@1.1
         packer
         pcre
         pkg-config
         python
         python3
         ranger
         readline
         reattach-to-user-namespace
         redis
         ruby
         s-lang
         sbt
         scala
         snort
         springboot
         sqlite
         squid
         ssh-copy-id
         sshfs
         supervisor
         terraform
         terraform-inventory
         the_silver_searcher
         thefuck
         tmux
         traefik
         trash-cli
         tree
         vault
         watch
         watchexec
         watchman
         webp
         wget
         wxmac
         xz
         zookeeper
         zsh
         zsh-completions
      )


   function instBrew (){
      #check is brew is installed, if not then install
         if [ ! -f "/usr/local/bin/brew" ]       # Check if file exists.
            then
         #   eval "$HOMEBREW[$@]"
             /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
         fi
   }

   function instInv () {
         for u in ${INVENTORY[@]}
            do /usr/local/bin/brew install "${u}"
	 done
   }

printf '%s\n' "${INVENTORY[@]}"

instBrew;
instInv;
